export enum FailureReason {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
  INVALID_2FA = 'INVALID_2FA',
  RATE_LIMITED = 'RATE_LIMITED',
  CAPTCHA_FAILED = 'CAPTCHA_FAILED',
  SUSPICIOUS_DEVICE = 'SUSPICIOUS_DEVICE'
}

export enum OtpType {
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  LOGIN_2FA = 'LOGIN_2FA',
  PASSWORD_RESET = 'PASSWORD_RESET',
  DEVICE_VERIFICATION = 'DEVICE_VERIFICATION'
}

export enum EventType {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  SUSPICIOUS_LOGIN = 'SUSPICIOUS_LOGIN',
  NEW_DEVICE = 'NEW_DEVICE',
  NEW_LOCATION = 'NEW_LOCATION',
  TWO_FA_ENABLED = 'TWO_FA_ENABLED',
  TWO_FA_DISABLED = 'TWO_FA_DISABLED',
  SESSION_EXPIRED = 'SESSION_EXPIRED'
}

export enum Severity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}
